stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_REGISTRY: 791763121716.dkr.ecr.ap-southeast-1.amazonaws.com
  SERVICE_NAME: user-service

docker-build:
  # Use the official docker image.
  image: docker:20.10.8
  stage: build  
  services:
    - docker:20.10.8-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t $DOCKER_REGISTRY/$SERVICE_NAME:latest .
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:latest
  # Run this job in master branch and a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      exists:
        - Dockerfile
